package typst-community:unicode-math-class@1.0.0;

interface types {
    /// <https://docs.rs/unicode-math-class/0.1.0/unicode_math_class/enum.MathClass.html>
    enum math-class {
        normal,
        alphabetic,
        binary,
        closing,
        diacritic,
        fence,
        glyph-part,
        large,
        opening,
        punctuation,
        relation,
        space,
        unary,
        vary,
        special,
    }
}

/// <https://docs.rs/unicode-math-class/0.1.0/unicode_math_class/>
world unicode-math-class {
    export types;
    use types.{math-class};

    /// <https://docs.rs/unicode-math-class/0.1.0/unicode_math_class/constant.REVISION.html>
    export revision: func() -> u8;

    /// <https://docs.rs/unicode-math-class/0.1.0/unicode_math_class/fn.class.html>
    export class: func(c: string) -> option<math-class>;
}
