name: deploy-pages
on:
  push:
    branches: "main"
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .vscode/**
      - tests/**
      - .github/**
      - "!.github/workflows/deploy-pages.yml"
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  deploy-pages:
    permissions:
      pages: write
      id-token: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-component -y
      - run: |
          cargo binstall --git https://github.com/bytecodealliance/wit-bindgen wit-bindgen-cli -y
      - id: configure-pages
        uses: actions/configure-pages@v4
      - run: make build
      - run: make build-docs
        env:
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
      - uses: actions/upload-pages-artifact@v3
      - id: deploy-pages
        uses: actions/deploy-pages@v4
