name: make build
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .vscode/**
      - .github/**
      - "!.github/workflows/make-build.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .vscode/**
      - .github/**
      - "!.github/workflows/make-build.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  COMPONENT_WORLD: unicode-math-class
jobs:
  make-build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-component -y
      - run: cargo binstall wasm-tools -y
      - run: make build
      - run: |
          wasm-tools component wit \
            target/wasm32-unknown-unknown/debug/${{ env.COMPONENT_WORLD }}.wasm \
            >> "$GITHUB_STEP_SUMMARY"
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            target/wasm32-unknown-unknown/debug/${{ env.COMPONENT_WORLD }}.wasm
