name: make publish
on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
jobs:
  make-publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: jcbhmr/setup-cargo-component@v1
      - run: make build RELEASE=1
      - run: make publish GHFLAGS="$GHFLAGS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHFLAGS: ${{ inputs.draft && '--draft' || '' }}
